export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOG_OUT_USER = 'LOG_OUT_USER';

export const EMAIL_VERIFICATION_REQUEST = 'EMAIL_VERIFICATION_REQUEST';
export const EMAIL_VERIFICATION_SUCCESS = 'EMAIL_VERIFICATION_SUCCESS';
export const EMAIL_VERIFICATION_FAILURE = 'EMAIL_VERIFICATION_FAILURE';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';
export const REGISTER_USER_CLEAR_ERORR = 'REGISTER_USER_CLEAR_ERORR';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const LOGIN_USER_CLEAR_ERROR = 'LOGIN_USER_CLEAR_ERROR';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const COMPANY_INVITE_REQUEST = 'COMPANY_INVITE_REQUEST';
export const COMPANY_INVITE_SUCCESS = 'COMPANY_INVITE_SUCCESS';
export const COMPANY_INVITE_FAILURE = 'COMPANY_INVITE_FAILURE';

export const COMPANY_INVITE_ACTION_LOADING = 'COMPANY_INVITE_ACTION_LOADING';
export const COMPANY_INVITE_ACCEPT = 'COMPANY_INVITE_ACCEPT';
export const COMPANY_INVITE_REJECT = 'COMPANY_INVITE_REJECT';
export const COMPANY_INVITE_ERROR = 'COMPANY_INVITE_ERROR';
export const COMPANY_INVITE_CLEAN = 'COMPANY_INVITE_CLEAN';
export const CHECK_ADMIN_REQUEST = 'CHECK_ADMIN_REQUEST';
export const CHECK_ADMIN_SUCCESS = 'CHECK_ADMIN_SUCCESS';
export const CHECK_ADMIN_FAILURE = 'CHECK_ADMIN_FAILURE';
export const SEND_INVITE_REQUEST = 'SEND_INVITE_REQUEST';
export const SEND_INVITE_SUCCESS = 'SEND_INVITE_SUCCESS';
export const SEND_INVITE_FAILURE = 'SEND_INVITE_FAILURE';

export const PENDING_QUESTIONNAIRES_LOADING = 'PENDING_QUESTIONNAIRES_LOADING';
export const PENDING_QUESTIONNAIRES_LOADED = 'PENDING_QUESTIONNAIRES_LOADED';
export const PENDING_QUESTIONNAIRES_ERROR = 'PENDING_QUESTIONNAIRES_ERROR';

export const QUESTIONNAIRE_LOADING = 'QUESTIONNAIRE_LOADING';
export const QUESTIONNAIRE_LOADED = 'QUESTIONNAIRE_LOADED';
export const QUESTIONNAIRE_ERROR = 'QUESTIONNAIRE_ERROR';

export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';
export const QUESTIONS_LOADED = 'QUESTIONS_LOADED';
export const QUESTIONS_ERROR = 'QUESTIONS_ERROR';

export const QUESTIONNAIRE_SUBMISSION_REQUEST =
  'QUESTIONNAIRE_SUBMISSION_REQUEST';
export const QUESTIONNAIRE_SUBMITTED = 'QUESTIONNAIRE_SUBMITTED';
export const QUESTIONNAIRE_SUBMISSION_ERROR = 'QUESTIONNAIRE_SUBMISSION_ERROR';
export const QUESTIONNAIRE_SUBMISSION_CLEAR = 'QUESTIONNAIRE_SUBMISSION_CLEAR';

export const ACTIVITY_LOADING = 'ACTIVITY_LOADING';
export const ACTIVITY_LOADED = 'ACTIVITY_LOADED';
export const ACTIVITY_QUESTIONNAIRE_RESPONSES_LOADED =
  'ACTIVITY_QUESTIONNAIRE_RESPONSES_LOADED';
export const ACTIVITY_ERROR = 'ACTIVITY_ERROR';

export const INVITE_LOADING = 'INVITE_LOADING';
export const INVITE_LOADED = 'INVITE_LOADED';
export const INVITE_ERROR = 'INVITE_ERROR';
export const INVITE_CLEAR = 'INVITE_CLEAR';

export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const TIP_LOADING = 'TIP_LOADING';
export const TIP_LOADED = 'TIP_LOADED';
export const TIP_ERROR = 'TIP_ERROR';

export const FORGOT_PASSWORD_CLEAR_SUCCESS = 'FORGOT_PASSWORD_CLEAR_SUCCESS';

export const REGISTER_USER_CLEAR_SUCCESS = 'REGISTER_USER_CLEAR_SUCCESS';

export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const COMPANY_INVITE_LIST_REQUEST = 'COMPANY_INVITE_LIST_REQUEST';
export const COMPANY_INVITE_LIST_SUCCESS = 'COMPANY_INVITE_LIST_SUCCESS';
export const COMPANY_INVITE_LIST_FAILURE = 'COMPANY_INVITE_LIST_FAILURE';
export const COMPANY_INVITE_LIST_CLEAR = 'COMPANY_INVITE_LIST_CLEAR';

export const MY_COMPANY_LIST_REQUEST = 'MY_COMPANY_LIST_REQUEST';
export const MY_COMPANY_LIST_SUCCESS = 'MY_COMPANY_LIST_SUCCESS';
export const MY_COMPANY_LIST_FAILURE = 'MY_COMPANY_LIST_FAILURE';
export const MY_COMPANY_LIST_CLEAR = 'MY_COMPANY_LIST_CLEAR';

export const JOINED_COMPANY_LIST_REQUEST = 'JOINED_COMPANY_LIST_REQUEST';
export const JOINED_COMPANY_LIST_SUCCESS = 'JOINED_COMPANY_LIST_SUCCESS';
export const JOINED_COMPANY_LIST_FAILURE = 'JOINED_COMPANY_LIST_FAILURE';
export const JOINED_COMPANY_LIST_CLEAR = 'JOINED_COMPANY_LIST_CLEAR';

export const MY_COMPANY_EMPLOYEES_REQUEST = 'MY_COMPANY_EMPLOYEES_REQUEST';
export const MY_COMPANY_EMPLOYEES_SUCCESS = 'MY_COMPANY_EMPLOYEES_SUCCESS';
export const MY_COMPANY_EMPLOYEES_FAILURE = 'MY_COMPANY_EMPLOYEES_FAILURE';
export const MY_COMPANY_EMPLOYEES_CLEAR = 'MY_COMPANY_EMPLOYEES_CLEAR';

export const REGISTER_COMPANY_REQUEST = 'REGISTER_COMPANY_REQUEST';
export const REGISTER_COMPANY_SUCCESS = 'REGISTER_COMPANY_SUCCESS';
export const REGISTER_COMPANY_FAILURE = 'REGISTER_COMPANY_FAILURE';
export const REGISTER_COMPANY_CLEAR = 'REGISTER_COMPANY_CLEAR';

export const HOME_LOADING = 'HOME_LOADING';
export const HOME_LOADED = 'HOME_LOADED';
export const HOME_ERROR = 'HOME_ERROR';

export const COMPANY_QUESTIONNAIRE_REQUEST = "COMPANY_QUESTIONNAIRE_REQUEST"
export const COMPANY_QUESTIONNAIRE_SUCCESS = "COMPANY_QUESTIONNAIRE_SUCCESS"
export const COMPANY_QUESTIONNAIRE_FAILURE = "COMPANY_QUESTIONNAIRE_FAILURE"

export const AVAILABLE_QUESTIONNAIRE_REQUEST = "AVAILABLE_QUESTIONNAIRE_REQUEST"
export const AVAILABLE_QUESTIONNAIRE_SUCCESS = "AVAILABLE_QUESTIONNAIRE_SUCCESS"
export const AVAILABLE_QUESTIONNAIRE_FAILURE = "AVAILABLE_QUESTIONNAIRE_FAILURE"

export const GET_QUESTIONNAIRE_DETAILS_REQUEST = "GET_QUESTIONNAIRE_DETAILS_REQUEST"
export const GET_QUESTIONNAIRE_DETAILS_SUCCESS = "GET_QUESTIONNAIRE_DETAILS_SUCCESS"
export const GET_QUESTIONNAIRE_DETAILS_FAILURE = "GET_QUESTIONNAIRE_DETAILS_FAILURE"


export const ADD_QUESTIONNAIRE_REQUEST = "ADD_QUESTIONNAIRE_REQUEST"
export const ADD_QUESTIONNAIRE_SUCCESS = "ADD_QUESTIONNAIRE_SUCCESS"
export const ADD_QUESTIONNAIRE_FAILURE = "ADD_QUESTIONNAIRE_FAILURE"
export const ADD_QUESTIONNAIRE_CLEAR = "ADD_QUESTIONNAIRE_CLEAR"

export const ADD_COMPANY_QUESTIONNIARE_RULE_REQUEST = "ADD_COMPANY_QUESTIONNIARE_RULE_REQUEST"
export const ADD_COMPANY_QUESTIONNIARE_RULE_SUCCESS = "ADD_COMPANY_QUESTIONNIARE_RULE_SUCCESS"
export const ADD_COMPANY_QUESTIONNIARE_RULE_FAILURE = "ADD_COMPANY_QUESTIONNIA_FAILURERE_RULE"
export const ADD_COMPANY_QUESTIONNAIRE_RULE_CLEAR = "ADD_COMPANY_QUESTIONNAIRE_RULE_CLEAR"

export const FETCH_QUESTIONNAIRE_RULE_LIST_REQUEST = "FETCH_QUESTIONNAIRE_RULE_LIST_REQUEST"
export const FETCH_QUESTIONNAIRE_RULE_LIST_SUCCESS = "FETCH_QUESTIONNAIRE_RULE_LIST_SUCCESS"
export const FETCH_QUESTIONNAIRE_RULE_LIST_FAILURE = "FETCH_QUESTIONNAIRE_RULE_LIST_FAILURE"

export const DELETE_RULE_REQUEST = "DELETE_RULE_REQUEST"
export const DELETE_RULE_SUCCESS = "DELETE_RULE_SUCCESS"
export const DELETE_RULE_FAILURE = "DELETE_RULE_FAILURE"
export const DELETE_RULE_CLEAR = "DELETE_RULE_CLEAR"

export const CHANGE_QUESTIONNAIRE_STATE_REQUEST = "CHANGE_QUESTIONNAIRE_STATE_REQUEST"
export const CHANGE_QUESTIONNAIRE_STATE_SUCCESS = "CHANGE_QUESTIONNAIRE_STATE_SUCCESS"
export const CHANGE_QUESTIONNAIRE_STATE_FAILURE = "CHANGE_QUESTIONNAIRE_STATE_FAILURE"
export const CHANGE_QUESTIONNAIRE_STATE_CLEAR = "CHANGE_QUESTIONNAIRE_STATE_CLEAR"
