const BASE_URL = process.env.REACT_APP_BACKEND_BASE_URL;
const ACCOUNTS_RESOURCE = `${BASE_URL}/accounts`;
const USER_ENDPOINT = `${ACCOUNTS_RESOURCE}/user/`;
const LOGIN_USER_ENDPOINT = `${ACCOUNTS_RESOURCE}/login/`;
const VERIFY_EMAIL_ENDPOINT = `${ACCOUNTS_RESOURCE}/verify`;
const FORGOT_PASSWORD_ENDPOINT = `${ACCOUNTS_RESOURCE}/forget/`;
const RESEND_MAIL_ENDPOINT = `${ACCOUNTS_RESOURCE}/resend/`;
const PROFILE_ENDPOINT = `${ACCOUNTS_RESOURCE}/profile/`;
const RESET_PASSWORD_ENDPOINT = `${ACCOUNTS_RESOURCE}/reset/`;

const COMPANIES_RESOURCE = `${BASE_URL}/companies`;
const COMPANY_DETAILS_ENDPOINT = `${COMPANIES_RESOURCE}/company-details`;
const ACCEPT_COMPANY_INVITE_ENDPOINT = `${COMPANIES_RESOURCE}/accept-company-invite/`;
const REJECT_COMPANY_INVITE_ENDPOINT = `${COMPANIES_RESOURCE}/cancel-company-invite/`;
const CHECK_COMPANY_ADMIN_ENDPOINT = `${COMPANIES_RESOURCE}/isAdmin/`;

const SURVEYS_RESOURCE = `${BASE_URL}/surveys`;
const PENDING_QUESTIONNAIRES = `${SURVEYS_RESOURCE}/pending/`;
const MANDATORY_QUESTIONNAIRES = `${SURVEYS_RESOURCE}/mandatory/`;
const QUESTIONNAIRE = `${SURVEYS_RESOURCE}/questionnaire/`;
const QUESTIONNAIRE_QUESTIONS = `${SURVEYS_RESOURCE}/questions/`;
const QUESTIONNAIRE_SUBMIT = `${SURVEYS_RESOURCE}/submit/`;
const QUESTIONNAIRE_SUBMISSIONS = `${SURVEYS_RESOURCE}/submission/`;
const QUESTIONNAIRE_QUESTION_RESPONSES = `${SURVEYS_RESOURCE}/question-responses/`;
const TIPS = `${SURVEYS_RESOURCE}/tips/`;

const COMMONS_RESOURCE = `${BASE_URL}/commons`;
const CREATE_INVITE = `${COMMONS_RESOURCE}/invite/`;
const ACCEPT_INVITE = `${COMMONS_RESOURCE}/accept/`;
const UPDATE_PASSWORD_ENDPOINT = `${ACCOUNTS_RESOURCE}/update-password/`;
const MY_COMPANIES_ENDPOINT = `${COMPANIES_RESOURCE}/my-companies/`;
const JOINED_COMPANIES_ENDPOINT = `${COMPANIES_RESOURCE}/joined-companies/`;
const REGISTER_COMPANY_ENDPOINT = `${BASE_URL}/companies/company/`;

const USER_COUNT = `${ACCOUNTS_RESOURCE}/user-counts/`;
const QUESTIONNAIRE_COUNT = `${SURVEYS_RESOURCE}/survey-counts/`;
const COMPANY_COUNT = `${COMPANIES_RESOURCE}/company-counts/`;

export {
  USER_ENDPOINT,
  LOGIN_USER_ENDPOINT,
  VERIFY_EMAIL_ENDPOINT,
  FORGOT_PASSWORD_ENDPOINT,
  RESEND_MAIL_ENDPOINT,
  PROFILE_ENDPOINT,
  RESET_PASSWORD_ENDPOINT,
  UPDATE_PASSWORD_ENDPOINT,
  COMPANIES_RESOURCE,
  MY_COMPANIES_ENDPOINT,
  PENDING_QUESTIONNAIRES,
  MANDATORY_QUESTIONNAIRES,
  QUESTIONNAIRE,
  QUESTIONNAIRE_QUESTIONS,
  QUESTIONNAIRE_SUBMIT,
  QUESTIONNAIRE_SUBMISSIONS,
  QUESTIONNAIRE_QUESTION_RESPONSES,
  TIPS,
  CREATE_INVITE,
  ACCEPT_INVITE,
  COMPANY_DETAILS_ENDPOINT,
  ACCEPT_COMPANY_INVITE_ENDPOINT,
  REJECT_COMPANY_INVITE_ENDPOINT,
  CHECK_COMPANY_ADMIN_ENDPOINT,
  JOINED_COMPANIES_ENDPOINT,
  USER_COUNT,
  QUESTIONNAIRE_COUNT,
  COMPANY_COUNT,
  REGISTER_COMPANY_ENDPOINT,
  SURVEYS_RESOURCE,
};
