const PHONE_NUMBER_PATTERN = "[7-9]{1}[0-9]{9}";
const DOB_PATTERN = "[1-9]{4}-[0-9]{2}-[0-9]{2}";
const PASSWORD_PATTERN_LENGTH = "[a-zA-Z0-9]{8,}";

export {
    PHONE_NUMBER_PATTERN,
    DOB_PATTERN,
    PASSWORD_PATTERN_LENGTH
}
